import { AppProvider } from "./components/layout/AppContext"; 
import Header from "./components/layout/Header";
import { Roboto } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: "GoTasty - 🥗🍛🍵",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth" style={{ overflow: 'auto', scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
      <head>
        <style>
          {`
            html::-webkit-scrollbar {
              display: none;
            }
          `}
        </style>
        <link rel="icon" type="image/x-icon" href="/fevicon.ico" />
        <link rel="shortcut icon" href="/fevicon.ico" type="image/x-icon" />
      </head>
      <body className={roboto.className}>
        <main className="max-w-5xl mx-auto p-4 ">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="border-t p-8 text-xs text-center mt-16">
              By continuing past this page, you agree to our Terms of Service, Cookie Policy, Privacy Policy and Content Policies. All trademarks are properties of their respective owners. 2008-2025 &copy;GoTasty™ Ltd. All rights reserved.
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
